### ISSUE TITLE
glitch about googly eyes on horse

### ISSUE THREAD

**Issue by syrun97** [iChun/GooglyEyes#14]
horse have googly eye on back not on "REAL" eye.

![2017-04-10_17 13 19](https://cloud.githubusercontent.com/assets/19798397/24852082/17922b40-1e11-11e7-8acc-7e23a940c860.png)
version:1.10.2-6.0.0 
at farming valley modpack version is 0.7.6

**Comment by iChun** [comment]
That's an Easter egg and a reference to how Hats puts hats on horses.
