### ISSUE TITLE
[1.10.2] Crash while browsing in N/JEI?

### ISSUE THREAD

**Issue by DeadSix27** [iChun/GooglyEyes#17]
Not sure what exactly caused it, but it happened as I typed stuff into JEI.

Crash log:
https://gist.github.com/DeadSix27/d1f27e336b87803eda518cca1952b804

Tell me if you need more than that.

**Comment by MUSE-iC** [comment]
I was about to post this as well. It seems to be a conflict with the OpenBlocks mod. I loaded up a new profile with just GooglyEyes and OpenBlocks and the crash still occurs.

https://pastebin.com/vXii63rM

**Comment by iChun** [comment]
Should be fixed in 7.0.1.

**Comment by ASpieler** [comment]
That's lovely iChun, but what about the version of Minecraft where the crash is actually occurring?
1.10.2 still has this issue, and will continue to have this issue until someone, you or someone else, doesn't matter to me, makes a patch for it.
