### ISSUE TITLE
[Request] Add variations of eyes.

### ISSUE THREAD

**Issue by ghost** [iChun/GooglyEyes#2]

**Comment by iChun** [comment]
What kind of variations are you looking for?

**Comment by ghost** [comment]
random eye colors and possibly dynamic eye "white" color, (blue inner eye makes a red outer eye), maybe something like this but darken the outer color a bit [https://hsto.org/getpro/geektimes/post_images/68e/d0c/ecf/68ed0cecf4f940eae3a9377a0a6e7d88.png](img)
