### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Sunekaer** [iChun/GooglyEyes#21]
https://paste.dimdev.org/inumiyicoq.css

**Comment by marvinside** [comment]
Same for me. See attached File for a full crash report.
Modpack is Stoneblock 2 (FTB)
I played yesterday without any issues, today i am unable to launch. Haven't changed anything.

[crash-2019-08-01_20.57.58-client.txt](https://github.com/iChun/GooglyEyes/files/3458286/crash-2019-08-01_20.57.58-client.txt)

**Comment by ASpieler** [comment]
same issue as Sunekaer:
```
java.lang.NullPointerException: null
	at me.ichun.mods.googlyeyes.common.core.EventHandler.onRendererSafeCompatibilityEvent(EventHandler.java:90)
```
GooglyEyes: 1.12.2-7.1.0
Forge: 14.23.5.2847
iChunUtil: 1.12.2-7.2.1

**Comment by iChun** [comment]
Alright, I suspect that there is a mod causing iChunUtil to fire an event prematurely which Googly Eyes relies on so I added a check in iChunUtil. It should be in the next update (which should be out over the next couple of days or so) for iChunUtil. Please let me know if the issue persists. I'll be closing this issue in the meantime.

https://github.com/iChun/iChunUtil/commit/d707b282b25502dfd36cc60296c9853f59ab0d24
