### ISSUE TITLE
Cave Spider Crash

### ISSUE THREAD

**Issue by WenXin20** [iChun/GooglyEyes#23]
`Minecraft v1.15.2`
`Forge v31.1.19`
`Googly Eyes v8.0.0`

My game crashed client-side while on my server due to rendering of the cave spider eyes. Other mobs render their googly eyes fine.
[Crash Report](https://gist.github.com/WenXin20/eab04a3a8d0c5a3e8820181c94fddc2a)

**Comment by iChun** [comment]
This was a really odd crash and I couldn't reproduce this, but I poked around the code and changed some stuff, could you try updating iChunUtil and Googly Eyes and let me know if this issue persists?

**Comment by WenXin20** [comment]
Thanks! I'll try to test it soon. With the version it crashed on, I only had it happen once so far, but that could simply be because that was the only time it spawned with googly eyes.
