### ISSUE TITLE
Bug w/ Sheared Sheep

### ISSUE THREAD

**Issue by PutABananaInYourEar1** [iChun/GooglyEyes#24]
![2021-05-02_21 58 36_2](https://user-images.githubusercontent.com/83568385/116842710-5552d980-ab92-11eb-9c62-19b33fcfa778.png)

After I sheared a sheep, the eyes went completely White.

Minor Bug

**Comment by iChun** [comment]
Not a bug. Intended to show the sheep's wool colour when they're sheared.
Try it out on a dyed sheep 😉
