### ISSUE TITLE
googly eyes are incorrectly located on llamas

### ISSUE THREAD

**Issue by istinkalot** [iChun/GooglyEyes#25]
The googly eyes are placed on the behinds of llamas instead of where the eyes should be.

![2021-05-19_15 44 05](https://user-images.githubusercontent.com/2610104/118894593-63eeff80-b8b9-11eb-946e-83e29cd5a928.png)

**Comment by iChun** [comment]
It's an Easter egg. Turn it off in the head tracker category of iChunUtil's
config

**Comment by istinkalot** [comment]
i see
